name: Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - uses: ./.github/actions/node-setup
      with:
        node-version: ${{ matrix.node }}

    - name: Test
      run: pnpm validate:all
